apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-name
  labels:
    name: {{ .Release.Name }}-name
    {{- template "labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-name
    spec:
      containers:
      - name: name
        image: {{ .Values.name.image }}:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /resources/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 15
        env:
        - name: {{ .Values.xray.env }}
          value: {{ .Values.xray.service }}
